backend:
  # name: test-repo
  name: github
  repo: chodorowicz/jan-walulik

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Claim", name: "claim", widget: "markdown" }
      - file: "src/pages/research-papers.md"
        label: "Resarch Papers Page"
        name: "research-papers"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "research-papers-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Categories", name: "categories", widget: "list" }
  - name: "books"
    label: "Books"
    folder: "src/pages/books"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "book-page",
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Text", name: "text", widget: "markdown" }
      - { label: "Publisher", name: "publisher", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Extra Badge", name: "extraBadge", widget: "image" }
      - {
          label: "Extra Content Left",
          name: "extraContentLeft",
          widget: "markdown",
        }
      - {
          label: "Extra Content Right",
          name: "extraContentRight",
          widget: "markdown",
        }
      - { label: "Extra Background", name: "extraBg", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
