backend:
  # name: test-repo
  name: github
  repo: chodorowicz/jan-walulik
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Title Tag", name: "titleTag", widget: "string" }
          - {
              label: "Description Tag",
              name: "descriptionTag",
              widget: "string",
            }
          - { label: "Claim", name: "claim", widget: "markdown" }
          - { label: "About", name: "about", widget: "markdown" }
          - {
              label: "About Resarch Papers",
              name: "aboutResearchPapers",
              widget: "markdown",
            }
      - file: "src/pages/research-papers.md"
        label: "Resarch Papers Page"
        name: "research-papers"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "research-papers-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Url", name: "slug", widget: "string" }
          - { label: "Title Tag", name: "titleTag", widget: "string" }
          - {
              label: "Description Tag",
              name: "descriptionTag",
              widget: "string",
            }
          - { label: "Categories", name: "categories", widget: "list" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/books.md"
        label: "Books Page"
        name: "books-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "books-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Url", name: "slug", widget: "string" }
          - { label: "Title Tag", name: "titleTag", widget: "string" }
          - {
              label: "Description Tag",
              name: "descriptionTag",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Url", name: "slug", widget: "string" }
          - { label: "Title Tag", name: "titleTag", widget: "string" }
          - {
              label: "Description Tag",
              name: "descriptionTag",
              widget: "string",
            }
          - { label: "About", name: "about", widget: "markdown" }
          - {
              label: "Research Teaching",
              name: "researchTeaching",
              widget: "markdown",
            }
          - { label: "Publications", name: "publications", widget: "markdown" }
          - { label: "Education Top", name: "educationTop", widget: "markdown" }
          - {
              label: "Education Bottom",
              name: "educationBottom",
              widget: "markdown",
            }
      - file: "src/pages/privacy-policy.md"
        label: "Privacy Policy"
        name: "privacy-policy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "simple-page",
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "books"
    label: "Books"
    folder: "src/pages/books"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "book-page",
        }
      - { label: "Title Tag", name: "titleTag", widget: "string" }
      - { label: "Description Tag", name: "descriptionTag", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Text", name: "text", widget: "markdown" }
      - { label: "Publisher", name: "publisher", widget: "string" }
      - { label: "Url", name: "slug", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Extra Badge",
          name: "extraBadge",
          widget: "image",
          required: false,
        }
      - {
          label: "Extra Content Left",
          name: "extraContentLeft",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Extra Content Right",
          name: "extraContentRight",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Extra Background",
          name: "extraBg",
          widget: "image",
          required: false,
        }
  - name: "research-papers"
    label: "Research Papers"
    folder: "src/pages/research-papers"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title Tag", name: "titleTag", widget: "string" }
      - { label: "Description Tag", name: "descriptionTag", widget: "string" }
      - { label: "Where", name: "where", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "research-paper",
        }
      - { label: "Url", name: "slug", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "date",
          default: "",
          format: "YYYY-MM-DD",
          dateFormat: "YYYY-MM-DD",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "other"
    label: "Other"
    files:
      - file: "src/content-other/email.json"
        label: "Email"
        name: "email"
        extension: "json"
        create: true
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
